### ISSUE TITLE
`dex-contract` NPM Module

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-contracts#325]
After a discussion with @anxolin today we decided to create an NPM package for `dex-contracts` that can be consumed by packages who want to interact with the smart contract on the network. A couple additional utility functions should be made available as they are closely coupled with the contract code itself.

The NPM module will provide:
- [x] The contract ABI (#323)
- [x] Type definitions for use with TypeScript (for Web3js) (#435)
- [x] Utility functions for encoding/decoding parameters and return values (like decoding orders) (#323)

This means that the NPM package should not have any dependencies and should all become devDependencies with the exception of what is needed for the utility functions (I suspect BN.js will be needed).

**Comment by fleupold** [comment]
@nlordell can this be closed?

**Comment by nlordell** [comment]
@fleupold Not yet. That reminds me I need to speak with @denisgranha about automatic deployment.
